# Indian Sign Language Detection


In [55]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

In [56]:
#Preprocessing of training set
train_datagen=ImageDataGenerator(rescale=1./255,
                                 shear_range=0.2,
                                zoom_range=0.2,
                                horizontal_flip=True)

In [57]:
#Training Set
training_set=train_datagen.flow_from_directory('dataset/training_set',
                                              target_size=(64,64),
                                              batch_size=32,
                                              class_mode='categorical')

Found 34357 images belonging to 35 classes.


In [58]:
#Test Set
test_datagen=ImageDataGenerator(rescale=1./255)
test_set=test_datagen.flow_from_directory('dataset/test_set',target_size=(64,64),
                                         class_mode='categorical')

Found 8388 images belonging to 35 classes.


In [59]:
#BUILDING CNN
#initialise CNN
cnn=tf.keras.models.Sequential()

In [60]:
#Convulation
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu',input_shape=[64,64,3]))

In [61]:
#Pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [62]:
#second layer
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [63]:
#Flatten
cnn.add(tf.keras.layers.Flatten())

In [64]:
#Full Connection
cnn.add(tf.keras.layers.Dense(units=110,activation='relu'))
cnn.add(tf.keras.layers.Dense(units=62,activation='relu'))


In [65]:
#Output Layers
cnn.add(tf.keras.layers.Dense(units=35,activation='softmax'))


# Training the CNN


In [66]:
#Compiling the CNN
cnn.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [67]:
#Training the model on dataset
cnn.fit(x = training_set, validation_data = test_set, epochs = 20)

Epoch 1/20
1074/1074 [==============================] - 408s 379ms/step - loss: 0.1913 - accuracy: 0.9511 - val_loss: 0.3987 - val_accuracy: 0.9517
Epoch 2/20
1074/1074 [==============================] - 169s 157ms/step - loss: 0.0144 - accuracy: 0.9967 - val_loss: 0.2106 - val_accuracy: 0.9515
Epoch 3/20
1074/1074 [==============================] - 185s 172ms/step - loss: 0.0061 - accuracy: 0.9989 - val_loss: 0.3136 - val_accuracy: 0.9709
Epoch 4/20
1074/1074 [==============================] - 170s 158ms/step - loss: 0.0045 - accuracy: 0.9990 - val_loss: 0.2137 - val_accuracy: 0.9794
Epoch 5/20
1074/1074 [==============================] - 168s 157ms/step - loss: 0.0061 - accuracy: 0.9983 - val_loss: 0.1785 - val_accuracy: 0.9735
Epoch 6/20
1074/1074 [==============================] - 143s 133ms/step - loss: 0.0040 - accuracy: 0.9991 - val_loss: 0.2281 - val_accuracy: 0.9763
Epoch 7/20
1074/1074 [==============================] - 139s 130ms/step - loss: 0.0032 - accuracy: 0.9990 - val_

In [82]:
#Making a single prediction
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('dataset\single_prediction\W.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
print(test_image)

[[[10. 12. 27.]
  [12. 15. 30.]
  [11. 14. 31.]
  ...
  [16. 14. 35.]
  [11. 17. 29.]
  [15. 41. 30.]]

 [[10. 12. 27.]
  [12. 15. 30.]
  [10. 13. 30.]
  ...
  [15. 13. 34.]
  [ 9. 15. 27.]
  [18. 44. 33.]]

 [[ 9. 11. 26.]
  [11. 14. 29.]
  [12. 15. 30.]
  ...
  [17. 15. 36.]
  [ 8. 14. 26.]
  [16. 42. 31.]]

 ...

 [[11.  7. 24.]
  [11.  7. 24.]
  [12.  8. 25.]
  ...
  [10.  1. 20.]
  [ 5.  5. 15.]
  [17. 35. 23.]]

 [[ 5.  9. 18.]
  [ 6. 11. 17.]
  [ 4.  9. 15.]
  ...
  [ 5.  5. 17.]
  [ 0. 10. 11.]
  [13. 40. 21.]]

 [[17. 39. 26.]
  [16. 38. 25.]
  [16. 38. 25.]
  ...
  [17. 37. 28.]
  [11. 40. 20.]
  [21. 67. 28.]]]


In [83]:
#expanding dimension to enable working of our model on batch specified
test_image = np.expand_dims(test_image, axis = 0)

In [26]:
print(test_image.shape)  #every row in new container is a batch

(1, 64, 64, 3)


In [84]:
#predicting test image
result = cnn.predict(test_image) 
print(result)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [28]:
training_set.class_indices


{'1': 0,
 '2': 1,
 '3': 2,
 '4': 3,
 '5': 4,
 '6': 5,
 '7': 6,
 '8': 7,
 '9': 8,
 'A': 9,
 'B': 10,
 'C': 11,
 'D': 12,
 'E': 13,
 'F': 14,
 'G': 15,
 'H': 16,
 'I': 17,
 'J': 18,
 'K': 19,
 'L': 20,
 'M': 21,
 'N': 22,
 'O': 23,
 'P': 24,
 'Q': 25,
 'R': 26,
 'S': 27,
 'T': 28,
 'U': 29,
 'V': 30,
 'W': 31,
 'X': 32,
 'Y': 33,
 'Z': 34}

In [85]:

for i in range(35):
    if (result[0][i]==1):
        index=i
if(index<=8):
    print(index+1)
else:
    print(chr(index+56))

W
